# Generated by Django 3.1.4 on 2020-12-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eemail', models.EmailField(max_length=200)),
                ('epassword', models.CharField(max_length=200)),
                ('eaddress', models.CharField(max_length=200)),
                ('ecity', models.CharField(max_length=200)),
                ('ezip', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Zip',
            new_name='zip',
        ),
    ]
